### ISSUE TITLE
Broken if opted out of redesign

### ISSUE THREAD

**Issue by Gasur** [nickrussler/Reddit-Link-Opener#15]
If you have opted out of redesign, the new update breaks the addon. Same goes for old.reddit.com

**Comment by jamesshapiro** [comment]
Hey Gasur, if you're looking for a temporary fix, I used the steps here to find and install version 1.6.0 of the extension:

https://www.quickfever.com/3586/install-older-version-of-chrome-extension/

**Comment by Gasur** [comment]
Appreciate it. Thanks!

**Comment by jamesshapiro** [comment]
Just to update this, the suggestion above is not viable, because the extension will still auto-update to 1.7.0.

A better solution is to clone this repository, reset head to 1.6.0, and then load the "src" folder as an unpacked extension in developer mode under chrome://extensions

That way it will not auto-update and you will get the 1.6.0 functionality as desired.

**Comment by Gasur** [comment]
Yeah, I just noticed that. Appreciate the new reply :)

**Comment by nickrussler** [comment]
I added support for the old layout, should work on both the old and the new layout now.
